version: '3'

services:

  php:
    build: .
    volumes:
      - .:/var/www/html
    environment:
      DATA_BASE_HOST: ${DATA_BASE_HOST}
      DATA_BASE_PORT: ${DATA_BASE_PORT}
      DATA_BASE_NAME: ${DATA_BASE_NAME}
      DATA_BASE_USER: ${DATA_BASE_USER}
      DATA_BASE_PASSWORD: ${DATA_BASE_PASSWORD}